/*
 * bin2c — convert a binary file into a C source file containing a
 *         const unsigned char array and a size_t size constant.
 *
 * Usage: bin2c <input_file> <output_file> <symbol_name>
 *
 * The generated file is included by the asset bundle index so all
 * game assets can be linked directly into the executable.
 * Built by CMake and called at build time for each asset file.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(int argc, char *argv[])
{
    if (argc != 4) {
        fprintf(stderr, "Usage: bin2c <input_file> <output_file> <symbol_name>\n");
        return 1;
    }

    const char *input_path  = argv[1];
    const char *output_path = argv[2];
    const char *symbol      = argv[3];

    FILE *fin = fopen(input_path, "rb");
    if (!fin) {
        fprintf(stderr, "bin2c: cannot open input '%s'\n", input_path);
        return 1;
    }

    FILE *fout = fopen(output_path, "w");
    if (!fout) {
        fprintf(stderr, "bin2c: cannot open output '%s'\n", output_path);
        fclose(fin);
        return 1;
    }

    fprintf(fout, "/* Auto-generated by bin2c — do not edit */\n");
    fprintf(fout, "#include <stddef.h>\n\n");
    fprintf(fout, "const unsigned char %s[] = {\n", symbol);

    size_t count = 0;
    int byte;
    while ((byte = fgetc(fin)) != EOF) {
        if (count % 16 == 0)
            fprintf(fout, "    ");
        fprintf(fout, "0x%02x,", (unsigned char)byte);
        count++;
        if (count % 16 == 0)
            fprintf(fout, "\n");
    }
    if (count % 16 != 0)
        fprintf(fout, "\n");

    fprintf(fout, "};\n\n");
    fprintf(fout, "const size_t %s_size = %zu;\n", symbol, count);

    fclose(fin);
    fclose(fout);
    return 0;
}
